spring.application.name=Drug-RAG-Service
server.port=8082
spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration

spring.ai.model.chat=openai
spring.ai.model.embedding=google-genai

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.chat.options.temperature=0.2

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.dimensions=768


spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.ai.vectorstore.pgvector.index-type=NONE
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.table-name=drug_vector_store
spring.ai.vectorstore.pgvector.dimensions=768

logging.level.org.springframework.ai=INFO
logging.level.org.springframework.jdbc=INFO


#MCP

spring.ai.mcp.server.type=sync
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.name=Drug-server
spring.ai.mcp.server.version=1.0.0


