spring.application.name=Drug-RAG-Service
server.port=8081
spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration

spring.ai.model.chat=openai
spring.ai.model.embedding=google-genai

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.chat.options.temperature=0.2

spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.dimensions=768


spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.ai.vectorstore.pgvector.index-type=NONE
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.table-name=drug_vector_store
spring.ai.vectorstore.pgvector.dimensions=768

logging.level.org.springframework.ai=INFO
logging.level.org.springframework.jdbc=INFO


