spring.application.name=RAG
server.port=8080
# Force model selection
spring.ai.model.embedding=ollama
spring.ai.model.chat=openai

# Ollama only for embeddings
spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.ollama.chat.enabled=false

# Groq only for chat
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.chat.options.temperature=0.2
spring.ai.openai.chat.options.max-tokens=400

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768

spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=postgres
spring.datasource.password=root