spring.application.name=Backend
spring.datasource.url=jdbc:mysql://localhost:3306/meditrack
spring.datasource.username=root
spring.datasource.password=Guddu@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.mongodb.uri=

gcp.project-id=
gcp.document-ai.location=us
gcp.document-ai.processor-id=
spring.cloud.gcp.credentials.location=classpath:keys/meditrack-
gcp.document-ai.processor-version=pretrained-foundation-model-v1.5-2025-05-05

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

gemini.api.key=
