spring.application.name=Backend
spring.datasource.url=jdbc:mysql://localhost:3307/meditrack
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.mongodb.uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST:localhost}:27017/Meds?authSource=admin


#old
#gcp.project-id=691682299527
#gcp.document-ai.location=us
#gcp.document-ai.processor-id=1a3a3d94530f61da
#spring.cloud.gcp.credentials.location=classpath:keys/meditrack-thesis-7708a298418e.json
#gcp.document-ai.processor-version=pretrained-foundation-model-v1.5-2025-05-05



#new
gcp.project-id=941875666862
gcp.document-ai.location=eu
gcp.document-ai.processor-id=91c1f8d4b87dcef
spring.cloud.gcp.credentials.location=classpath:keys/meditrack-thesis-7708a298418e.json
#gcp.document-ai.processor-version=pretrained-foundation-model-v1.5-2025-05-05


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

groq.api.key=${GROQ_API_KEY_BACKEND}
groq.model=openai/gpt-oss-120b

#MCP

spring.ai.mcp.server.type=sync
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.name=Backend-server
spring.ai.mcp.server.version=1.0.0